// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "GitHub SSH Keys": Client
//
// Command:
// $ goagen
// --design=github.com/JKhawaja/rest-example/ssot
// --out=$(GOPATH)\src\github.com\JKhawaja\rest-example
// --version=v1.3.0

package client

import (
	"github.com/goadesign/goa"
	goaclient "github.com/goadesign/goa/client"
	"github.com/goadesign/goa/encoding/json"
)

// Client is the GitHub SSH Keys service client.
type Client struct {
	*goaclient.Client
	Encoder *goa.HTTPEncoder
	Decoder *goa.HTTPDecoder
}

// New instantiates the client.
func New(c goaclient.Doer) *Client {
	client := &Client{
		Client:  goaclient.New(c),
		Encoder: goa.NewHTTPEncoder(),
		Decoder: goa.NewHTTPDecoder(),
	}

	// Setup encoders and decoders
	client.Encoder.Register(json.NewEncoder, "application/json")
	client.Decoder.Register(json.NewDecoder, "application/json")

	// Setup default encoder and decoder
	client.Encoder.Register(json.NewEncoder, "*/*")
	client.Decoder.Register(json.NewDecoder, "*/*")

	return client
}
