// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "GitHub SSH Keys": Application User Types
//
// Command:
// $ goagen
// --design=github.com/JKhawaja/replicated/design
// --out=$(GOPATH)\src\github.com\JKhawaja\replicated
// --version=v1.2.0-dirty

package client

// Type for a GitHub user's public SSH Key
type userKey struct {
	// The ID of the public SSH key on GitHub.
	ID *int `form:"id,omitempty" json:"id,omitempty" xml:"id,omitempty"`
	// The public SSH key
	Key *string `form:"key,omitempty" json:"key,omitempty" xml:"key,omitempty"`
}

// Publicize creates UserKey from userKey
func (ut *userKey) Publicize() *UserKey {
	var pub UserKey
	if ut.ID != nil {
		pub.ID = ut.ID
	}
	if ut.Key != nil {
		pub.Key = ut.Key
	}
	return &pub
}

// Type for a GitHub user's public SSH Key
type UserKey struct {
	// The ID of the public SSH key on GitHub.
	ID *int `form:"id,omitempty" json:"id,omitempty" xml:"id,omitempty"`
	// The public SSH key
	Key *string `form:"key,omitempty" json:"key,omitempty" xml:"key,omitempty"`
}
