consumes:
- application/json
definitions:
  Keys:
    description: Response Type for a GitHub User's list of public SSH Keys (default
      view)
    example:
      keys:
      - id: 1.234568e+09
        key: ssh-rsa ABC123 ...
      - id: 1.234568e+09
        key: ssh-rsa ABC123 ...
      username: myname
    properties:
      keys:
        description: The list of the Github user's public SSH keys.
        example:
        - id: 1.234568e+09
          key: ssh-rsa ABC123 ...
        - id: 1.234568e+09
          key: ssh-rsa ABC123 ...
        items:
          $ref: '#/definitions/UserKey'
        type: array
      username:
        description: The username of the GitHub user.
        example: myname
        type: string
    required:
    - username
    - keys
    title: 'Mediatype identifier: application/vnd.keys+json; view=default'
    type: object
  KeysCollection:
    description: KeysCollection is the media type for an array of Keys (default view)
    example:
    - keys:
      - id: 1.234568e+09
        key: ssh-rsa ABC123 ...
      - id: 1.234568e+09
        key: ssh-rsa ABC123 ...
      username: myname
    - keys:
      - id: 1.234568e+09
        key: ssh-rsa ABC123 ...
      - id: 1.234568e+09
        key: ssh-rsa ABC123 ...
      username: myname
    items:
      $ref: '#/definitions/Keys'
    title: 'Mediatype identifier: application/vnd.keys+json; type=collection; view=default'
    type: array
  ListKeysPayload:
    example:
    - Explicabo quis quisquam ut consequatur.
    items:
      example: Explicabo quis quisquam ut consequatur.
      type: string
    title: ListKeysPayload
    type: array
  UserKey:
    description: Type for a GitHub user's public SSH Key
    example:
      id: 1.234568e+09
      key: ssh-rsa ABC123 ...
    properties:
      id:
        description: The ID of the public SSH key on GitHub.
        example: 1.234568e+09
        format: int64
        type: integer
      key:
        description: The public SSH key
        example: ssh-rsa ABC123 ...
        type: string
    title: UserKey
    type: object
info:
  description: This API is for retrieving lists of public SSH keys based on github
    usernames.
  title: GitHub SSH Keys
  version: 0.0.1
paths:
  /keys:
    post:
      description: Given a list of GitHub usernames, responds with list of public
        SSH keys for each User (associated to their GitHub account).
      operationId: keys#list
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/ListKeysPayload'
      produces:
      - application/vnd.keys+json; type=collection
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/KeysCollection'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      schemes:
      - http
      summary: List public SSH Keys based on username (or set of usernames)
      tags:
      - keys
produces:
- application/json
schemes:
- http
swagger: "2.0"
