// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "GitHub SSH Keys": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/JKhawaja/rest-example/ssot
// --out=$(GOPATH)\src\github.com\JKhawaja\rest-example\controllers
// --version=v1.3.0

package app
