// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "GitHub SSH Keys": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/JKhawaja/rest-example/design
// --out=$(GOPATH)\src\github.com\JKhawaja\rest-example
// --version=v1.2.0-dirty

package app
