// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "GitHub SSH Keys": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/JKhawaja/replicated/design
// --out=$(GOPATH)\src\github.com\JKhawaja\replicated
// --version=v1.2.0-dirty

package app

import (
	"github.com/goadesign/goa"
)

// Response Type for a GitHub User's list of public SSH Keys (default view)
//
// Identifier: application/vnd.keys+json; view=default
type Keys struct {
	// The list of the Github user's public SSH keys.
	Keys []*UserKey `form:"keys" json:"keys" xml:"keys"`
	// The username of the GitHub user.
	Username string `form:"username" json:"username" xml:"username"`
}

// Validate validates the Keys media type instance.
func (mt *Keys) Validate() (err error) {
	if mt.Username == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "username"))
	}
	if mt.Keys == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "keys"))
	}
	return
}

// KeysCollection is the media type for an array of Keys (default view)
//
// Identifier: application/vnd.keys+json; type=collection; view=default
type KeysCollection []*Keys

// Validate validates the KeysCollection media type instance.
func (mt KeysCollection) Validate() (err error) {
	for _, e := range mt {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	return
}
